In [42]:
#lin alg
import numpy as np

#csv IOs and dataframes
import pandas as pd

#clustering
from sklearn.cluster import KMeans
from FixedKmeans import same_size_kmeans

import matplotlib.pyplot as plt

%matplotlib notebook

## Same-Sized K-means or Classic K-means

When performing K-means, we will use the same-size version, which gives equal family sizes at the cost of fit.

Adjust the number of families using `num_families`.

In [43]:
num_families = 6

## Data Cleaning

In [44]:
#This can be a relative or absolute path. In actual work it will very highly on your envoirment
df = pd.read_csv('family_matching.csv')

#initialize sets to exlude or drop later
drop_cols = set([])
id_cols = set([])

In [45]:
#get shape of survey data
df.shape

(40, 46)

#### Print out the full csv

In [46]:
df

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,2No2Yes/No2/No2 7:49:YesNo PM EST,REDACTED,A,A,Yes,Yes,Yes,No,No,No,...,No,Yes,Yes,No,No,Yes,Yes,Yes,No,Yes
1,2No2Yes/No2/No2 7:49:Yes2 PM EST,REDACTED,B,A,Yes,No,Yes,No,No,Yes,...,No,Yes,No,Yes,No,No,No,Yes,Yes,No
2,2No2Yes/No2/No2 7:49:Yes4 PM EST,REDACTED,C,A,No,Yes,No,No,No,No,...,No,Yes,Yes,Yes,Yes,Yes,No,No,No,Yes
3,2No2Yes/No2/No2 7:49:Yes9 PM EST,REDACTED,D,A,No,No,Yes,Yes,No,Yes,...,Yes,Yes,No,Yes,No,Yes,No,No,Yes,Yes
4,2No2Yes/No2/No2 7:49:22 PM EST,REDACTED,E,A,Yes,No,Yes,Yes,Yes,No,...,No,No,Yes,No,No,Yes,No,No,Yes,Yes
5,2No2Yes/No2/No2 7:49:3No PM EST,REDACTED,F,A,No,No,No,Yes,No,Yes,...,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,Yes
6,2No2Yes/No2/No2 7:49:45 PM EST,REDACTED,G,A,No,No,Yes,Yes,Yes,Yes,...,No,No,Yes,No,No,Yes,Yes,No,No,Yes
7,2No2Yes/No2/No2 7:5No:No6 PM EST,REDACTED,H,A,Yes,No,Yes,No,No,Yes,...,No,No,No,No,No,No,Yes,No,Yes,Yes
8,2No2Yes/No2/No2 7:5No:No8 PM EST,REDACTED,I,A,Yes,Yes,No,Yes,No,Yes,...,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,No
9,2No2Yes/No2/No2 7:5No:YesYes PM EST,REDACTED,J,A,Yes,Yes,Yes,Yes,No,Yes,...,Yes,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes
10,2No2Yes/No2/No2 7:5No:27 PM EST,REDACTED,K,A,No,Yes,No,Yes,No,Yes,...,Yes,No,Yes,Yes,No,Yes,Yes,No,Yes,No
11,2No2Yes/No2/No2 7:5No:56 PM EST,REDACTED,L,A,No,No,Yes,Yes,Yes,No,...,No,Yes,No,Yes,No,No,Yes,Yes,No,Yes
12,2No2Yes/No2/No2 7:5Yes:No5 PM EST,REDACTED,M,A,Yes,No,Yes,Yes,Yes,Yes,...,No,No,Yes,Yes,Yes,No,Yes,Yes,No,No
13,2No2Yes/No2/No2 7:5Yes:28 PM EST,REDACTED,N,A,No,Yes,Yes,No,Yes,No,...,No,No,No,No,Yes,Yes,Yes,No,Yes,Yes
14,2No2Yes/No2/No2 7:5Yes:32 PM EST,REDACTED,O,A,Yes,No,Yes,Yes,Yes,No,...,No,No,Yes,Yes,Yes,No,No,No,Yes,No
15,2No2Yes/No2/No2 7:5Yes:32 PM EST,REDACTED,P,A,Yes,No,Yes,No,Yes,No,...,Yes,Yes,No,Yes,No,Yes,No,No,No,No
16,2No2Yes/No2/No2 7:5Yes:32 PM EST,REDACTED,Q,A,No,No,Yes,Yes,Yes,No,...,No,No,No,No,Yes,Yes,No,No,No,No
17,2No2Yes/No2/No2 7:52:Yes9 PM EST,REDACTED,R,A,Yes,No,Yes,Yes,No,Yes,...,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes
18,2No2Yes/No2/No2 7:52:24 PM EST,REDACTED,S,A,No,No,Yes,No,No,No,...,No,Yes,Yes,No,No,No,Yes,No,No,No
19,2No2Yes/No2/No2 7:52:26 PM EST,REDACTED,T,A,Yes,No,Yes,Yes,Yes,No,...,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes
20,2No2Yes/No2/No2 7:52:38 PM EST,REDACTED,U,A,Yes,No,No,No,Yes,Yes,...,Yes,No,No,No,Yes,Yes,Yes,Yes,No,Yes
21,2No2Yes/No2/No2 7:52:43 PM EST,REDACTED,V,A,No,Yes,Yes,No,No,Yes,...,Yes,Yes,Yes,No,Yes,No,Yes,No,Yes,No
22,2No2Yes/No2/No2 7:52:5Yes PM EST,REDACTED,W,A,Yes,Yes,Yes,Yes,No,Yes,...,Yes,No,Yes,No,Yes,Yes,No,No,Yes,No
23,2No2Yes/No2/No2 7:53:Yes7 PM EST,REDACTED,X,A,No,Yes,No,Yes,No,Yes,...,No,Yes,No,Yes,No,No,Yes,Yes,No,No
24,2No2Yes/No2/No2 7:53:48 PM EST,REDACTED,Y,A,No,No,No,No,No,Yes,...,Yes,Yes,Yes,No,Yes,No,No,Yes,Yes,No
25,2No2Yes/No2/No2 7:54:2Yes PM EST,REDACTED,Z,A,Yes,No,No,No,No,No,...,Yes,No,Yes,Yes,Yes,Yes,No,No,No,Yes
26,2No2Yes/No2/No2 7:54:27 PM EST,REDACTED,A,B,Yes,Yes,Yes,Yes,No,Yes,...,Yes,Yes,Yes,No,Yes,No,Yes,Yes,Yes,Yes
27,2No2Yes/No2/No2 7:55:No3 PM EST,REDACTED,B,B,No,No,No,No,No,Yes,...,Yes,Yes,No,Yes,No,No,Yes,No,No,Yes
28,2No2Yes/No2/No2 7:59:22 PM EST,REDACTED,C,B,No,No,Yes,No,Yes,No,...,No,No,No,Yes,Yes,No,Yes,Yes,No,Yes
29,2No2Yes/No2/No2 9:23:42 PM EST,REDACTED,D,B,No,No,Yes,No,No,No,...,Yes,Yes,No,Yes,Yes,Yes,No,Yes,No,No
30,2No2Yes/No2/No2 9:4No:53 PM EST,REDACTED,E,B,No,Yes,Yes,Yes,Yes,Yes,...,Yes,Yes,No,No,No,No,Yes,Yes,Yes,Yes
31,2No2Yes/No2/No2 9:57:29 PM EST,REDACTED,F,B,Yes,Yes,No,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,Yes,Yes,No,No,No
32,2No2Yes/No2/No3 Yes:22:25 PM EST,REDACTED,G,B,Yes,Yes,Yes,Yes,Yes,No,...,Yes,No,No,No,No,Yes,Yes,No,No,No
33,2No2Yes/No2/No9 2:No7:Yes4 PM EST,REDACTED,H,B,Yes,Yes,No,Yes,No,Yes,...,Yes,No,No,No,No,No,No,Yes,Yes,No
34,2No2Yes/No2/No9 2:No9:54 PM EST,REDACTED,I,B,No,No,Yes,No,Yes,Yes,...,No,Yes,No,No,Yes,Yes,No,No,No,Yes
35,2No2Yes/No2/No9 2:2Yes:Yes5 PM EST,REDACTED,J,B,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,No,No,No,No,No,No,No,Yes,No
36,2No2Yes/No2/No9 2:2Yes:53 PM EST,REDACTED,K,B,No,Yes,Yes,No,Yes,No,...,Yes,Yes,No,No,No,No,No,No,No,No
37,2No2Yes/No2/No9 2:3Yes:29 PM EST,REDACTED,L,B,No,Yes,Yes,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,Yes,Yes,No,Yes,No
38,2No2Yes/No2/No9 7:NoNo:56 PM EST,REDACTED,M,B,No,Yes,No,Yes,Yes,Yes,...,Yes,Yes,No,No,No,No,No,Yes,No,No
39,2No2Yes/No2/No9 7:No8:55 PM EST,REDACTED,N,B,Yes,No,Yes,Yes,Yes,Yes,...,Yes,No,No,No,No,No,Yes,No,No,No

In [47]:
df.head()

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,2No2Yes/No2/No2 7:49:YesNo PM EST,REDACTED,A,A,Yes,Yes,Yes,No,No,No,...,No,Yes,Yes,No,No,Yes,Yes,Yes,No,Yes
1,2No2Yes/No2/No2 7:49:Yes2 PM EST,REDACTED,B,A,Yes,No,Yes,No,No,Yes,...,No,Yes,No,Yes,No,No,No,Yes,Yes,No
2,2No2Yes/No2/No2 7:49:Yes4 PM EST,REDACTED,C,A,No,Yes,No,No,No,No,...,No,Yes,Yes,Yes,Yes,Yes,No,No,No,Yes
3,2No2Yes/No2/No2 7:49:Yes9 PM EST,REDACTED,D,A,No,No,Yes,Yes,No,Yes,...,Yes,Yes,No,Yes,No,Yes,No,No,Yes,Yes
4,2No2Yes/No2/No2 7:49:22 PM EST,REDACTED,E,A,Yes,No,Yes,Yes,Yes,No,...,No,No,Yes,No,No,Yes,No,No,Yes,Yes

Timestamps are not relevant to our family matching so we will just drop this column.

In [48]:
#add timestamp column to drop_cols set

drop_cols.add('Timestamp')

#### Our first three columns are all identifier data

In [49]:
df[['Username', 'First Name', 'Last Name']]

    Username First Name Last Name
0   REDACTED          A         A
1   REDACTED          B         A
2   REDACTED          C         A
3   REDACTED          D         A
4   REDACTED          E         A
5   REDACTED          F         A
6   REDACTED          G         A
7   REDACTED          H         A
8   REDACTED          I         A
9   REDACTED          J         A
10  REDACTED          K         A
11  REDACTED          L         A
12  REDACTED          M         A
13  REDACTED          N         A
14  REDACTED          O         A
15  REDACTED          P         A
16  REDACTED          Q         A
17  REDACTED          R         A
18  REDACTED          S         A
19  REDACTED          T         A
20  REDACTED          U         A
21  REDACTED          V         A
22  REDACTED          W         A
23  REDACTED          X         A
24  REDACTED          Y         A
25  REDACTED          Z         A
26  REDACTED          A         B
27  REDACTED          B         B
28  REDACTED          C         B
29  REDACTED          D         B
30  REDACTED          E         B
31  REDACTED          F         B
32  REDACTED          G         B
33  REDACTED          H         B
34  REDACTED          I         B
35  REDACTED          J         B
36  REDACTED          K         B
37  REDACTED          L         B
38  REDACTED          M         B
39  REDACTED          N         B

We will store this data separately for use in identifying our matching results later, but it will not be run through k-means.

In [50]:
id_cols = set(['Username', 'First Name', 'Last Name'])

In [51]:
# We will convert all of our 'No'/'Yes' values to 0/1 values
for question in df:
    if(not question in id_cols and not question in drop_cols):
        df[question] = df[question].apply(lambda x: 0 if x=='No' else 1)

In [52]:
df

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,2No2Yes/No2/No2 7:49:YesNo PM EST,REDACTED,A,A,1,1,1,0,0,0,...,0,1,1,0,0,1,1,1,0,1
1,2No2Yes/No2/No2 7:49:Yes2 PM EST,REDACTED,B,A,1,0,1,0,0,1,...,0,1,0,1,0,0,0,1,1,0
2,2No2Yes/No2/No2 7:49:Yes4 PM EST,REDACTED,C,A,0,1,0,0,0,0,...,0,1,1,1,1,1,0,0,0,1
3,2No2Yes/No2/No2 7:49:Yes9 PM EST,REDACTED,D,A,0,0,1,1,0,1,...,1,1,0,1,0,1,0,0,1,1
4,2No2Yes/No2/No2 7:49:22 PM EST,REDACTED,E,A,1,0,1,1,1,0,...,0,0,1,0,0,1,0,0,1,1
5,2No2Yes/No2/No2 7:49:3No PM EST,REDACTED,F,A,0,0,0,1,0,1,...,1,1,0,1,1,0,1,0,1,1
6,2No2Yes/No2/No2 7:49:45 PM EST,REDACTED,G,A,0,0,1,1,1,1,...,0,0,1,0,0,1,1,0,0,1
7,2No2Yes/No2/No2 7:5No:No6 PM EST,REDACTED,H,A,1,0,1,0,0,1,...,0,0,0,0,0,0,1,0,1,1
8,2No2Yes/No2/No2 7:5No:No8 PM EST,REDACTED,I,A,1,1,0,1,0,1,...,1,1,1,0,1,1,1,1,1,0
9,2No2Yes/No2/No2 7:5No:YesYes PM EST,REDACTED,J,A,1,1,1,1,0,1,...,1,0,0,0,1,1,1,1,1,1
10,2No2Yes/No2/No2 7:5No:27 PM EST,REDACTED,K,A,0,1,0,1,0,1,...,1,0,1,1,0,1,1,0,1,0
11,2No2Yes/No2/No2 7:5No:56 PM EST,REDACTED,L,A,0,0,1,1,1,0,...,0,1,0,1,0,0,1,1,0,1
12,2No2Yes/No2/No2 7:5Yes:No5 PM EST,REDACTED,M,A,1,0,1,1,1,1,...,0,0,1,1,1,0,1,1,0,0
13,2No2Yes/No2/No2 7:5Yes:28 PM EST,REDACTED,N,A,0,1,1,0,1,0,...,0,0,0,0,1,1,1,0,1,1
14,2No2Yes/No2/No2 7:5Yes:32 PM EST,REDACTED,O,A,1,0,1,1,1,0,...,0,0,1,1,1,0,0,0,1,0
15,2No2Yes/No2/No2 7:5Yes:32 PM EST,REDACTED,P,A,1,0,1,0,1,0,...,1,1,0,1,0,1,0,0,0,0
16,2No2Yes/No2/No2 7:5Yes:32 PM EST,REDACTED,Q,A,0,0,1,1,1,0,...,0,0,0,0,1,1,0,0,0,0
17,2No2Yes/No2/No2 7:52:Yes9 PM EST,REDACTED,R,A,1,0,1,1,0,1,...,0,0,0,0,1,1,1,1,1,1
18,2No2Yes/No2/No2 7:52:24 PM EST,REDACTED,S,A,0,0,1,0,0,0,...,0,1,1,0,0,0,1,0,0,0
19,2No2Yes/No2/No2 7:52:26 PM EST,REDACTED,T,A,1,0,1,1,1,0,...,1,0,0,1,1,0,0,1,0,1
20,2No2Yes/No2/No2 7:52:38 PM EST,REDACTED,U,A,1,0,0,0,1,1,...,1,0,0,0,1,1,1,1,0,1
21,2No2Yes/No2/No2 7:52:43 PM EST,REDACTED,V,A,0,1,1,0,0,1,...,1,1,1,0,1,0,1,0,1,0
22,2No2Yes/No2/No2 7:52:5Yes PM EST,REDACTED,W,A,1,1,1,1,0,1,...,1,0,1,0,1,1,0,0,1,0
23,2No2Yes/No2/No2 7:53:Yes7 PM EST,REDACTED,X,A,0,1,0,1,0,1,...,0,1,0,1,0,0,1,1,0,0
24,2No2Yes/No2/No2 7:53:48 PM EST,REDACTED,Y,A,0,0,0,0,0,1,...,1,1,1,0,1,0,0,1,1,0
25,2No2Yes/No2/No2 7:54:2Yes PM EST,REDACTED,Z,A,1,0,0,0,0,0,...,1,0,1,1,1,1,0,0,0,1
26,2No2Yes/No2/No2 7:54:27 PM EST,REDACTED,A,B,1,1,1,1,0,1,...,1,1,1,0,1,0,1,1,1,1
27,2No2Yes/No2/No2 7:55:No3 PM EST,REDACTED,B,B,0,0,0,0,0,1,...,1,1,0,1,0,0,1,0,0,1
28,2No2Yes/No2/No2 7:59:22 PM EST,REDACTED,C,B,0,0,1,0,1,0,...,0,0,0,1,1,0,1,1,0,1
29,2No2Yes/No2/No2 9:23:42 PM EST,REDACTED,D,B,0,0,1,0,0,0,...,1,1,0,1,1,1,0,1,0,0
30,2No2Yes/No2/No2 9:4No:53 PM EST,REDACTED,E,B,0,1,1,1,1,1,...,1,1,0,0,0,0,1,1,1,1
31,2No2Yes/No2/No2 9:57:29 PM EST,REDACTED,F,B,1,1,0,0,1,1,...,1,1,1,1,0,1,1,0,0,0
32,2No2Yes/No2/No3 Yes:22:25 PM EST,REDACTED,G,B,1,1,1,1,1,0,...,1,0,0,0,0,1,1,0,0,0
33,2No2Yes/No2/No9 2:No7:Yes4 PM EST,REDACTED,H,B,1,1,0,1,0,1,...,1,0,0,0,0,0,0,1,1,0
34,2No2Yes/No2/No9 2:No9:54 PM EST,REDACTED,I,B,0,0,1,0,1,1,...,0,1,0,0,1,1,0,0,0,1
35,2No2Yes/No2/No9 2:2Yes:Yes5 PM EST,REDACTED,J,B,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0,1,0
36,2No2Yes/No2/No9 2:2Yes:53 PM EST,REDACTED,K,B,0,1,1,0,1,0,...,1,1,0,0,0,0,0,0,0,0
37,2No2Yes/No2/No9 2:3Yes:29 PM EST,REDACTED,L,B,0,1,1,0,1,1,...,1,1,1,1,0,1,1,0,1,0
38,2No2Yes/No2/No9 7:NoNo:56 PM EST,REDACTED,M,B,0,1,0,1,1,1,...,1,1,0,0,0,0,0,1,0,0
39,2No2Yes/No2/No9 7:No8:55 PM EST,REDACTED,N,B,1,0,1,1,1,1,...,1,0,0,0,0,0,1,0,0,0

### Delete drop columns

In [53]:
df.drop(drop_cols, axis=1,inplace=True)

In [54]:
df

,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,REDACTED,A,A,1,1,1,0,0,0,0,...,0,1,1,0,0,1,1,1,0,1
1,REDACTED,B,A,1,0,1,0,0,1,0,...,0,1,0,1,0,0,0,1,1,0
2,REDACTED,C,A,0,1,0,0,0,0,0,...,0,1,1,1,1,1,0,0,0,1
3,REDACTED,D,A,0,0,1,1,0,1,1,...,1,1,0,1,0,1,0,0,1,1
4,REDACTED,E,A,1,0,1,1,1,0,0,...,0,0,1,0,0,1,0,0,1,1
5,REDACTED,F,A,0,0,0,1,0,1,1,...,1,1,0,1,1,0,1,0,1,1
6,REDACTED,G,A,0,0,1,1,1,1,0,...,0,0,1,0,0,1,1,0,0,1
7,REDACTED,H,A,1,0,1,0,0,1,1,...,0,0,0,0,0,0,1,0,1,1
8,REDACTED,I,A,1,1,0,1,0,1,1,...,1,1,1,0,1,1,1,1,1,0
9,REDACTED,J,A,1,1,1,1,0,1,1,...,1,0,0,0,1,1,1,1,1,1
10,REDACTED,K,A,0,1,0,1,0,1,0,...,1,0,1,1,0,1,1,0,1,0
11,REDACTED,L,A,0,0,1,1,1,0,0,...,0,1,0,1,0,0,1,1,0,1
12,REDACTED,M,A,1,0,1,1,1,1,0,...,0,0,1,1,1,0,1,1,0,0
13,REDACTED,N,A,0,1,1,0,1,0,1,...,0,0,0,0,1,1,1,0,1,1
14,REDACTED,O,A,1,0,1,1,1,0,1,...,0,0,1,1,1,0,0,0,1,0
15,REDACTED,P,A,1,0,1,0,1,0,1,...,1,1,0,1,0,1,0,0,0,0
16,REDACTED,Q,A,0,0,1,1,1,0,0,...,0,0,0,0,1,1,0,0,0,0
17,REDACTED,R,A,1,0,1,1,0,1,1,...,0,0,0,0,1,1,1,1,1,1
18,REDACTED,S,A,0,0,1,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
19,REDACTED,T,A,1,0,1,1,1,0,1,...,1,0,0,1,1,0,0,1,0,1
20,REDACTED,U,A,1,0,0,0,1,1,1,...,1,0,0,0,1,1,1,1,0,1
21,REDACTED,V,A,0,1,1,0,0,1,1,...,1,1,1,0,1,0,1,0,1,0
22,REDACTED,W,A,1,1,1,1,0,1,1,...,1,0,1,0,1,1,0,0,1,0
23,REDACTED,X,A,0,1,0,1,0,1,1,...,0,1,0,1,0,0,1,1,0,0
24,REDACTED,Y,A,0,0,0,0,0,1,0,...,1,1,1,0,1,0,0,1,1,0
25,REDACTED,Z,A,1,0,0,0,0,0,1,...,1,0,1,1,1,1,0,0,0,1
26,REDACTED,A,B,1,1,1,1,0,1,1,...,1,1,1,0,1,0,1,1,1,1
27,REDACTED,B,B,0,0,0,0,0,1,1,...,1,1,0,1,0,0,1,0,0,1
28,REDACTED,C,B,0,0,1,0,1,0,1,...,0,0,0,1,1,0,1,1,0,1
29,REDACTED,D,B,0,0,1,0,0,0,0,...,1,1,0,1,1,1,0,1,0,0
30,REDACTED,E,B,0,1,1,1,1,1,0,...,1,1,0,0,0,0,1,1,1,1
31,REDACTED,F,B,1,1,0,0,1,1,0,...,1,1,1,1,0,1,1,0,0,0
32,REDACTED,G,B,1,1,1,1,1,0,0,...,1,0,0,0,0,1,1,0,0,0
33,REDACTED,H,B,1,1,0,1,0,1,0,...,1,0,0,0,0,0,0,1,1,0
34,REDACTED,I,B,0,0,1,0,1,1,0,...,0,1,0,0,1,1,0,0,0,1
35,REDACTED,J,B,1,1,1,1,1,1,0,...,1,0,0,0,0,0,0,0,1,0
36,REDACTED,K,B,0,1,1,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
37,REDACTED,L,B,0,1,1,0,1,1,0,...,1,1,1,1,0,1,1,0,1,0
38,REDACTED,M,B,0,1,0,1,1,1,1,...,1,1,0,0,0,0,0,1,0,0
39,REDACTED,N,B,1,0,1,1,1,1,1,...,1,0,0,0,0,0,1,0,0,0

# Inferencing

#### Seperate the data from the ids for now

In [55]:
X, X_data = df, df.drop(id_cols, axis=1)

In [56]:
X

,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,REDACTED,A,A,1,1,1,0,0,0,0,...,0,1,1,0,0,1,1,1,0,1
1,REDACTED,B,A,1,0,1,0,0,1,0,...,0,1,0,1,0,0,0,1,1,0
2,REDACTED,C,A,0,1,0,0,0,0,0,...,0,1,1,1,1,1,0,0,0,1
3,REDACTED,D,A,0,0,1,1,0,1,1,...,1,1,0,1,0,1,0,0,1,1
4,REDACTED,E,A,1,0,1,1,1,0,0,...,0,0,1,0,0,1,0,0,1,1
5,REDACTED,F,A,0,0,0,1,0,1,1,...,1,1,0,1,1,0,1,0,1,1
6,REDACTED,G,A,0,0,1,1,1,1,0,...,0,0,1,0,0,1,1,0,0,1
7,REDACTED,H,A,1,0,1,0,0,1,1,...,0,0,0,0,0,0,1,0,1,1
8,REDACTED,I,A,1,1,0,1,0,1,1,...,1,1,1,0,1,1,1,1,1,0
9,REDACTED,J,A,1,1,1,1,0,1,1,...,1,0,0,0,1,1,1,1,1,1
10,REDACTED,K,A,0,1,0,1,0,1,0,...,1,0,1,1,0,1,1,0,1,0
11,REDACTED,L,A,0,0,1,1,1,0,0,...,0,1,0,1,0,0,1,1,0,1
12,REDACTED,M,A,1,0,1,1,1,1,0,...,0,0,1,1,1,0,1,1,0,0
13,REDACTED,N,A,0,1,1,0,1,0,1,...,0,0,0,0,1,1,1,0,1,1
14,REDACTED,O,A,1,0,1,1,1,0,1,...,0,0,1,1,1,0,0,0,1,0
15,REDACTED,P,A,1,0,1,0,1,0,1,...,1,1,0,1,0,1,0,0,0,0
16,REDACTED,Q,A,0,0,1,1,1,0,0,...,0,0,0,0,1,1,0,0,0,0
17,REDACTED,R,A,1,0,1,1,0,1,1,...,0,0,0,0,1,1,1,1,1,1
18,REDACTED,S,A,0,0,1,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
19,REDACTED,T,A,1,0,1,1,1,0,1,...,1,0,0,1,1,0,0,1,0,1
20,REDACTED,U,A,1,0,0,0,1,1,1,...,1,0,0,0,1,1,1,1,0,1
21,REDACTED,V,A,0,1,1,0,0,1,1,...,1,1,1,0,1,0,1,0,1,0
22,REDACTED,W,A,1,1,1,1,0,1,1,...,1,0,1,0,1,1,0,0,1,0
23,REDACTED,X,A,0,1,0,1,0,1,1,...,0,1,0,1,0,0,1,1,0,0
24,REDACTED,Y,A,0,0,0,0,0,1,0,...,1,1,1,0,1,0,0,1,1,0
25,REDACTED,Z,A,1,0,0,0,0,0,1,...,1,0,1,1,1,1,0,0,0,1
26,REDACTED,A,B,1,1,1,1,0,1,1,...,1,1,1,0,1,0,1,1,1,1
27,REDACTED,B,B,0,0,0,0,0,1,1,...,1,1,0,1,0,0,1,0,0,1
28,REDACTED,C,B,0,0,1,0,1,0,1,...,0,0,0,1,1,0,1,1,0,1
29,REDACTED,D,B,0,0,1,0,0,0,0,...,1,1,0,1,1,1,0,1,0,0
30,REDACTED,E,B,0,1,1,1,1,1,0,...,1,1,0,0,0,0,1,1,1,1
31,REDACTED,F,B,1,1,0,0,1,1,0,...,1,1,1,1,0,1,1,0,0,0
32,REDACTED,G,B,1,1,1,1,1,0,0,...,1,0,0,0,0,1,1,0,0,0
33,REDACTED,H,B,1,1,0,1,0,1,0,...,1,0,0,0,0,0,0,1,1,0
34,REDACTED,I,B,0,0,1,0,1,1,0,...,0,1,0,0,1,1,0,0,0,1
35,REDACTED,J,B,1,1,1,1,1,1,0,...,1,0,0,0,0,0,0,0,1,0
36,REDACTED,K,B,0,1,1,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
37,REDACTED,L,B,0,1,1,0,1,1,0,...,1,1,1,1,0,1,1,0,1,0
38,REDACTED,M,B,0,1,0,1,1,1,1,...,1,1,0,0,0,0,0,1,0,0
39,REDACTED,N,B,1,0,1,1,1,1,1,...,1,0,0,0,0,0,1,0,0,0

In [57]:
X_data

,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,Do you like playing sports?,Do your hobbies fall within the arts?,Do you do a lot of outdoor activities?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,1,1,1,0,0,0,0,0,1,0,...,0,1,1,0,0,1,1,1,0,1
1,1,0,1,0,0,1,0,0,0,1,...,0,1,0,1,0,0,0,1,1,0
2,0,1,0,0,0,0,0,0,1,1,...,0,1,1,1,1,1,0,0,0,1
3,0,0,1,1,0,1,1,0,0,1,...,1,1,0,1,0,1,0,0,1,1
4,1,0,1,1,1,0,0,0,1,1,...,0,0,1,0,0,1,0,0,1,1
5,0,0,0,1,0,1,1,0,0,1,...,1,1,0,1,1,0,1,0,1,1
6,0,0,1,1,1,1,0,0,0,0,...,0,0,1,0,0,1,1,0,0,1
7,1,0,1,0,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,1,1
8,1,1,0,1,0,1,1,1,1,0,...,1,1,1,0,1,1,1,1,1,0
9,1,1,1,1,0,1,1,0,0,1,...,1,0,0,0,1,1,1,1,1,1
10,0,1,0,1,0,1,0,1,0,1,...,1,0,1,1,0,1,1,0,1,0
11,0,0,1,1,1,0,0,1,0,1,...,0,1,0,1,0,0,1,1,0,1
12,1,0,1,1,1,1,0,1,1,0,...,0,0,1,1,1,0,1,1,0,0
13,0,1,1,0,1,0,1,1,0,1,...,0,0,0,0,1,1,1,0,1,1
14,1,0,1,1,1,0,1,0,0,1,...,0,0,1,1,1,0,0,0,1,0
15,1,0,1,0,1,0,1,1,1,0,...,1,1,0,1,0,1,0,0,0,0
16,0,0,1,1,1,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,0
17,1,0,1,1,0,1,1,0,0,1,...,0,0,0,0,1,1,1,1,1,1
18,0,0,1,0,0,0,0,0,0,1,...,0,1,1,0,0,0,1,0,0,0
19,1,0,1,1,1,0,1,0,1,0,...,1,0,0,1,1,0,0,1,0,1
20,1,0,0,0,1,1,1,0,1,0,...,1,0,0,0,1,1,1,1,0,1
21,0,1,1,0,0,1,1,0,0,1,...,1,1,1,0,1,0,1,0,1,0
22,1,1,1,1,0,1,1,1,0,1,...,1,0,1,0,1,1,0,0,1,0
23,0,1,0,1,0,1,1,1,0,1,...,0,1,0,1,0,0,1,1,0,0
24,0,0,0,0,0,1,0,1,0,1,...,1,1,1,0,1,0,0,1,1,0
25,1,0,0,0,0,0,1,1,1,0,...,1,0,1,1,1,1,0,0,0,1
26,1,1,1,1,0,1,1,1,0,0,...,1,1,1,0,1,0,1,1,1,1
27,0,0,0,0,0,1,1,1,0,0,...,1,1,0,1,0,0,1,0,0,1
28,0,0,1,0,1,0,1,0,1,0,...,0,0,0,1,1,0,1,1,0,1
29,0,0,1,0,0,0,0,0,0,0,...,1,1,0,1,1,1,0,1,0,0
30,0,1,1,1,1,1,0,1,1,1,...,1,1,0,0,0,0,1,1,1,1
31,1,1,0,0,1,1,0,0,0,0,...,1,1,1,1,0,1,1,0,0,0
32,1,1,1,1,1,0,0,0,1,1,...,1,0,0,0,0,1,1,0,0,0
33,1,1,0,1,0,1,0,0,1,1,...,1,0,0,0,0,0,0,1,1,0
34,0,0,1,0,1,1,0,1,0,0,...,0,1,0,0,1,1,0,0,0,1
35,1,1,1,1,1,1,0,1,1,1,...,1,0,0,0,0,0,0,0,1,0
36,0,1,1,0,1,0,0,1,0,1,...,1,1,0,0,0,0,0,0,0,0
37,0,1,1,0,1,1,0,0,0,1,...,1,1,1,1,0,1,1,0,1,0
38,0,1,0,1,1,1,1,0,1,0,...,1,1,0,0,0,0,0,1,0,0
39,1,0,1,1,1,1,1,1,1,1,...,1,0,0,0,0,0,1,0,0,0

### Kmeans perfromed using the following [api](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html)

In [58]:
model = same_size_kmeans(X_data, k=6, size_flexibility=0, max_iter=10)

In [59]:
 X['Labels'] = model.cluster_id

In [60]:
X

,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,...,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Labels
0,REDACTED,A,A,1,1,1,0,0,0,0,...,1,1,0,0,1,1,1,0,1,5
1,REDACTED,B,A,1,0,1,0,0,1,0,...,1,0,1,0,0,0,1,1,0,5
2,REDACTED,C,A,0,1,0,0,0,0,0,...,1,1,1,1,1,0,0,0,1,5
3,REDACTED,D,A,0,0,1,1,0,1,1,...,1,0,1,0,1,0,0,1,1,5
4,REDACTED,E,A,1,0,1,1,1,0,0,...,0,1,0,0,1,0,0,1,1,3
5,REDACTED,F,A,0,0,0,1,0,1,1,...,1,0,1,1,0,1,0,1,1,3
6,REDACTED,G,A,0,0,1,1,1,1,0,...,0,1,0,0,1,1,0,0,1,3
7,REDACTED,H,A,1,0,1,0,0,1,1,...,0,0,0,0,0,1,0,1,1,3
8,REDACTED,I,A,1,1,0,1,0,1,1,...,1,1,0,1,1,1,1,1,0,3
9,REDACTED,J,A,1,1,1,1,0,1,1,...,0,0,0,1,1,1,1,1,1,3
10,REDACTED,K,A,0,1,0,1,0,1,0,...,0,1,1,0,1,1,0,1,0,4
11,REDACTED,L,A,0,0,1,1,1,0,0,...,1,0,1,0,0,1,1,0,1,0
12,REDACTED,M,A,1,0,1,1,1,1,0,...,0,1,1,1,0,1,1,0,0,0
13,REDACTED,N,A,0,1,1,0,1,0,1,...,0,0,0,1,1,1,0,1,1,0
14,REDACTED,O,A,1,0,1,1,1,0,1,...,0,1,1,1,0,0,0,1,0,0
15,REDACTED,P,A,1,0,1,0,1,0,1,...,1,0,1,0,1,0,0,0,0,1
16,REDACTED,Q,A,0,0,1,1,1,0,0,...,0,0,0,1,1,0,0,0,0,5
17,REDACTED,R,A,1,0,1,1,0,1,1,...,0,0,0,1,1,1,1,1,1,5
18,REDACTED,S,A,0,0,1,0,0,0,0,...,1,1,0,0,0,1,0,0,0,0
19,REDACTED,T,A,1,0,1,1,1,0,1,...,0,0,1,1,0,0,1,0,1,0
20,REDACTED,U,A,1,0,0,0,1,1,1,...,0,0,0,1,1,1,1,0,1,2
21,REDACTED,V,A,0,1,1,0,0,1,1,...,1,1,0,1,0,1,0,1,0,4
22,REDACTED,W,A,1,1,1,1,0,1,1,...,0,1,0,1,1,0,0,1,0,4
23,REDACTED,X,A,0,1,0,1,0,1,1,...,1,0,1,0,0,1,1,0,0,4
24,REDACTED,Y,A,0,0,0,0,0,1,0,...,1,1,0,1,0,0,1,1,0,4
25,REDACTED,Z,A,1,0,0,0,0,0,1,...,0,1,1,1,1,0,0,0,1,4
26,REDACTED,A,B,1,1,1,1,0,1,1,...,1,1,0,1,0,1,1,1,1,3
27,REDACTED,B,B,0,0,0,0,0,1,1,...,1,0,1,0,0,1,0,0,1,4
28,REDACTED,C,B,0,0,1,0,1,0,1,...,0,0,1,1,0,1,1,0,1,0
29,REDACTED,D,B,0,0,1,0,0,0,0,...,1,0,1,1,1,0,1,0,0,2
30,REDACTED,E,B,0,1,1,1,1,1,0,...,1,0,0,0,0,1,1,1,1,2
31,REDACTED,F,B,1,1,0,0,1,1,0,...,1,1,1,0,1,1,0,0,0,2
32,REDACTED,G,B,1,1,1,1,1,0,0,...,0,0,0,0,1,1,0,0,0,2
33,REDACTED,H,B,1,1,0,1,0,1,0,...,0,0,0,0,0,0,1,1,0,2
34,REDACTED,I,B,0,0,1,0,1,1,0,...,1,0,0,1,1,0,0,0,1,1
35,REDACTED,J,B,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,1,0,1
36,REDACTED,K,B,0,1,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
37,REDACTED,L,B,0,1,1,0,1,1,0,...,1,1,1,0,1,1,0,1,0,1
38,REDACTED,M,B,0,1,0,1,1,1,1,...,1,0,0,0,0,0,1,0,0,1
39,REDACTED,N,B,1,0,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,1

Now we add the family labels and return the final families

In [61]:
families = {}
families['Euclid'] = []
families['Prim'] = []
families['Hopper'] = []
families['Pascal'] = []
families['Boole'] = []
families['Djikstra'] = []

for i in range(len(X['Labels'])):
    if(X['Labels'][i] == 0):
        families['Euclid'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 1):
        families['Prim'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 2):
        families['Hopper'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 3):
        families['Pascal'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 4):
        families['Boole'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 5):
        families['Djikstra'].append(X['First Name'][i] + ' ' + X['Last Name'][i])

for family in families:
    print(family)
    print(families[family])
    print()

Euclid
['L A', 'M A', 'N A', 'O A', 'S A', 'T A', 'C B']

Prim
['P A', 'I B', 'J B', 'K B', 'L B', 'M B', 'N B']

Hopper
['U A', 'D B', 'E B', 'F B', 'G B', 'H B']

Pascal
['E A', 'F A', 'G A', 'H A', 'I A', 'J A', 'A B']

Boole
['K A', 'V A', 'W A', 'X A', 'Y A', 'Z A', 'B B']

Djikstra
['A A', 'B A', 'C A', 'D A', 'Q A', 'R A']